apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-spostgresql'
  labels:
    component: spostgresql
    project: '{{ .Chart.Name }}'
    release: '{{ .Release.Name }}'
  annotations:
    docker-compose-sha1: 16e51bd9928b2de1c735e032cedc3f7440a44684
    version: 2.0.0-beta2
spec:
  selector:
    component: spostgresql
    release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
