apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-swebapp'
  labels:
    component: swebapp
    project: '{{ .Chart.Name }}'
    release: '{{ .Release.Name }}'
  annotations:
    docker-compose-sha1: 16e51bd9928b2de1c735e032cedc3f7440a44684
    version: 2.0.0-beta2
spec:
  type: ClusterIP
  selector:
    component: swebapp
    release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
